import slide1 from "../assets/Mapslide/slide1.png";
import slide3 from "../assets/Mapslide/slide3.png";
import slide4 from "../assets/Mapslide/tiktok.png";
import slide5 from "../assets/Mapslide/slide5.png";
import slide6 from "../assets/Mapslide/slide6.png";
import slide7 from "../assets/Mapslide/ikonsb.png";
import slide9 from "../assets/Mapslide/slide9.png";
import slide12 from "../assets/Mapslide/slide12.png";
import slide11 from "../assets/Mapslide/mac.png";
import slide10 from "../assets/Mapslide/slide10.png";

export const MapSlider = [
  {
    image: slide9,
    name: "map.map1",
    title: "map.map2",
    country: "map.map6",
    id: 1,
  },
  {
    image: slide1,
    name: "map.map4",
    title: "map.map5",
    country: "map.map6",
    id: 2,
  },
  {
    image: slide3,
    name: "map.map7",
    title: "map.map8",
    country: "map.map6",
    id: 3,
  },
  {
    image: slide4,
    name: "map.map11",
    title: "map.map9",
    country: "map.map6",
    id: 4,
  },
  {
    image: slide5,
    name: "map.map1",
    title: "map.map10",
    country: "map.map6",
    id: 5,
  },
  {
    image: slide6,
    name: "map.map11",
    title: "Grimes Inc",
    country: "map.map6",
    id: 6,
  },
  {
    image: slide1,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 7,
  },
  {
    image: slide7,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 8,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 9,
  },
  {
    image: slide10,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 10,
  },
  {
    image: slide11,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 11,
  },
  {
    image: slide12,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 12,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map2",
    country: "map.map6",
    id: 1,
  },
  {
    image: slide1,
    name: "map.map4",
    title: "map.map5",
    country: "map.map6",
    id: 2,
  },
  {
    image: slide3,
    name: "map.map7",
    title: "map.map8",
    country: "map.map6",
    id: 3,
  },
  {
    image: slide4,
    name: "map.map11",
    title: "map.map9",
    country: "map.map6",
    id: 4,
  },
  {
    image: slide5,
    name: "map.map1",
    title: "map.map10",
    country: "map.map6",
    id: 5,
  },
  {
    image: slide6,
    name: "map.map11",
    title: "Grimes Inc",
    country: "map.map6",
    id: 6,
  },
  {
    image: slide1,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 7,
  },
  {
    image: slide7,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 8,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 9,
  },
  {
    image: slide10,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 10,
  },
  {
    image: slide11,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 11,
  },
  {
    image: slide12,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 12,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map2",
    country: "map.map6",
    id: 1,
  },
  {
    image: slide1,
    name: "map.map4",
    title: "map.map5",
    country: "map.map6",
    id: 2,
  },
  {
    image: slide3,
    name: "map.map7",
    title: "map.map8",
    country: "map.map6",
    id: 3,
  },
  {
    image: slide4,
    name: "map.map11",
    title: "map.map9",
    country: "map.map6",
    id: 4,
  },
  {
    image: slide5,
    name: "map.map1",
    title: "map.map10",
    country: "map.map6",
    id: 5,
  },
  {
    image: slide6,
    name: "map.map11",
    title: "Grimes Inc",
    country: "map.map6",
    id: 6,
  },
  {
    image: slide1,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 7,
  },
  {
    image: slide7,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 8,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 9,
  },
  {
    image: slide10,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 10,
  },
  {
    image: slide11,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 11,
  },
  {
    image: slide12,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 12,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map2",
    country: "map.map6",
    id: 1,
  },
  {
    image: slide1,
    name: "map.map4",
    title: "map.map5",
    country: "map.map6",
    id: 2,
  },
  {
    image: slide3,
    name: "map.map7",
    title: "map.map8",
    country: "map.map6",
    id: 3,
  },
  {
    image: slide4,
    name: "map.map11",
    title: "map.map9",
    country: "map.map6",
    id: 4,
  },
  {
    image: slide5,
    name: "map.map1",
    title: "map.map10",
    country: "map.map6",
    id: 5,
  },
  {
    image: slide6,
    name: "map.map11",
    title: "Grimes Inc",
    country: "map.map6",
    id: 6,
  },
  {
    image: slide1,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 7,
  },
  {
    image: slide7,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 8,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 9,
  },
  {
    image: slide10,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 10,
  },
  {
    image: slide11,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 11,
  },
  {
    image: slide12,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 12,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map2",
    country: "map.map6",
    id: 1,
  },
  {
    image: slide1,
    name: "map.map4",
    title: "map.map5",
    country: "map.map6",
    id: 2,
  },
  {
    image: slide3,
    name: "map.map7",
    title: "map.map8",
    country: "map.map6",
    id: 3,
  },
  {
    image: slide4,
    name: "map.map11",
    title: "map.map9",
    country: "map.map6",
    id: 4,
  },
  {
    image: slide5,
    name: "map.map1",
    title: "map.map10",
    country: "map.map6",
    id: 5,
  },
  {
    image: slide6,
    name: "map.map11",
    title: "Grimes Inc",
    country: "map.map6",
    id: 6,
  },
  {
    image: slide1,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 7,
  },
  {
    image: slide7,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 8,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 9,
  },
  {
    image: slide10,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 10,
  },
  {
    image: slide11,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 11,
  },
  {
    image: slide12,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 12,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map2",
    country: "map.map6",
    id: 1,
  },
  {
    image: slide1,
    name: "map.map4",
    title: "map.map5",
    country: "map.map6",
    id: 2,
  },
  {
    image: slide3,
    name: "map.map7",
    title: "map.map8",
    country: "map.map6",
    id: 3,
  },
  {
    image: slide4,
    name: "map.map11",
    title: "map.map9",
    country: "map.map6",
    id: 4,
  },
  {
    image: slide5,
    name: "map.map1",
    title: "map.map10",
    country: "map.map6",
    id: 5,
  },
  {
    image: slide6,
    name: "map.map11",
    title: "Grimes Inc",
    country: "map.map6",
    id: 6,
  },
  {
    image: slide1,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 7,
  },
  {
    image: slide7,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 8,
  },
  {
    image: slide9,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 9,
  },
  {
    image: slide10,
    name: "map.map13",
    title: "map.map14",
    country: "map.map6",
    id: 10,
  },
  {
    image: slide11,
    name: "map.map1",
    title: "map.map15",
    country: "map.map6",
    id: 11,
  },
  {
    image: slide12,
    name: "map.map1",
    title: "map.map16",
    country: "map.map6",
    id: 12,
  },
];
